# Generated by Django 3.1.6 on 2021-02-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_title', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('ans5', models.TextField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinexam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('is_instructor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Answer',
            fields=[
                ('student_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_number', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinexam.exam')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinexam.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinexam.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('question_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_number', models.IntegerField()),
                ('point', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinexam.exam')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinexam.question')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinexam.user'),
        ),
    ]
