# Generated by Django 3.1.6 on 2021-02-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinexam', '0002_auto_20210220_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ans1',
            new_name='answer_A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ans2',
            new_name='answer_B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ans3',
            new_name='answer_C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ans4',
            new_name='answer_D',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ans5',
            new_name='answer_E',
        ),
    ]
